### ISSUE TITLE
Can't skip adding labels

### ISSUE THREAD

**Issue by mbabker** [do-community/hacktoberfest-repo-topic-apply#11]
The `--labels` option [defaults to true](https://github.com/do-community/hacktoberfest-repo-topic-apply/blob/a776e52dbb1cc6ce851b493454ef96e7655f0e47/main.go#L35), meaning the tool will always attempt to add labels regardless of whether the option is included or not.

**Comment by Zelgius** [comment]
This was fixed in #17
