### ISSUE TITLE
--dry-run is always true

### ISSUE THREAD

**Issue by bastelfreak** [do-community/hacktoberfest-repo-topic-apply#22]
hey, I just tried this locally with the following command:
```
hfest-repo --access-token ** --gh-org voxpupuli --include-forks
```

and it prints this output:

```
...
   • [dryrun] adding topic     repo=puppet-rkhunter topic=hacktoberfest
   • [dryrun] adding topic     repo=facterdb topic=hacktoberfest
   • [dryrun] adding topic     repo=puppet-earlyoom topic=hacktoberfest
   • [dryrun] adding topic     repo=puppet-config topic=hacktoberfest
   • [dryrun] adding topic     repo=puppet-format topic=hacktoberfest
   • [dryrun] adding topic     repo=voxpupuli-acceptance topic=hacktoberfest
   • [dryrun] adding topic     repo=pdksync_config topic=hacktoberfest
   • [dryrun] adding topic     repo=containers topic=hacktoberfest
...
```

afterwards I checked the cmdline parsing: 
https://github.com/do-community/hacktoberfest-repo-topic-apply/blob/eb60aa3ed48c9b46a739886a81707eaa81f18ead/main.go#L38

dryrun defaults to true. Is that a bug? according to the README.md, dry-run is opt-in so it should default to false? Or maybe I'm just missing too much sleep ¯\_(ツ)_/¯

**Comment by Zelgius** [comment]
Thanks for catching this! I've merged it in a we have a new build
